version: '3'
services:
  jupyter_pytorch:
    build:
      context: .
      args:
        - YOUR_UID=${YOUR_UID}
        - YOUR_GID=${YOUR_GID}
        - CONTAINER_USER_NAME=${CONTAINER_USER_NAME}
        - CONTAINER_USER_PASSWORD=${CONTAINER_USER_PASSWORD}
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    ports:
      - '${JUPYTER_PORT}:8888'
    volumes:
      - ${HOME}:/home/${CONTAINER_USER_NAME}/@HOST_HOME
      - ${HOME}/.jupyter:/home/${CONTAINER_USER_NAME}/.jupyter
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]